In [2]:
import sys
import tensorflow.keras
import pandas as pd
import sklearn as sk
import scipy as sp
import tensorflow as tf
import platform
print(f"Python Platform: {platform.platform()}")
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
print(f"SciPy {sp.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print(gpu)
print("GPU is", "available" if gpu else "NOT AVAILABLE")

Python Platform: macOS-13.0-arm64-arm-64bit
Tensor Flow Version: 2.11.0
Keras Version: 2.11.0

Python 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]
Pandas 1.5.3
Scikit-Learn 1.2.2
SciPy 1.10.1
True
GPU is available


In [8]:
import pandas as pd


df = pd.DataFrame({'number_a':[13,-12,14,-14,14,15,-13,-13,-15,14,14,-14,13,-12,-14,15],
                  'number_b':[14,13,13,-13,-13,12,11,-15,12,12,-12,-15,-13,14,-12,-12],
                   'label_c' :[0,3,None,None,1,0,3,2,None,0,1,2,None,3,2,1] })

df

number_a  number_b  label_c
0         13        14      0.0
1        -12        13      3.0
2         14        13      NaN
3        -14       -13      NaN
4         14       -13      1.0
5         15        12      0.0
6        -13        11      3.0
7        -13       -15      2.0
8        -15        12      NaN
9         14        12      0.0
10        14       -12      1.0
11       -14       -15      2.0
12        13       -13      NaN
13       -12        14      3.0
14       -14       -12      2.0
15        15       -12      1.0

In [13]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3, 
                     weights='uniform', 
                     metric='nan_euclidean')

imputer.fit(df)
Xtrans = imputer.transform(df)
Xtrans[:,2]


array([0., 3., 0., 2., 1., 0., 3., 2., 3., 0., 1., 2., 1., 3., 2., 1.])

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
import numpy as np
x = np.array([4, 6, 9, 2])
y = np.log(x)
y

array([1.38629436, 1.79175947, 2.19722458, 0.69314718])

In [4]:
from math import log2

class0 = 20/100
class1 = 80/100

i1 = -(class0 * log2(class0) + class1 * log2(class1))
i2 = -(class1 * log2(class0) + class0 * log2(class1))
i3 = class0 * log2(class0) - class1 * log2(class1)
i4 = class1 * log2(class1) - class0 * log2(class0)

print( i1, i2, i3, i4)

0.7219280948873623 1.9219280948873623 -0.2068431430675826 0.2068431430675826


In [6]:
e = 2.465
y2 = x**e
y2

array([ 30.48441594,  82.82145048, 225.01309109,   5.52126941])